### PR TITLE
fix: adding optional parameters to contructor

### LINKED ISSUE #978: False-positive when adding optional parameter to constructor
Example: https://github.com/yiisoft/log/pull/128

Before:

```php
public function __construct()
{
    // ...
}
```

After:

```php
public function __construct(array $levels = [])
{
    // ...
}
```

Result:

```
[BC] ADDED: Parameter levels was added to Method __construct() of class Yiisoft\Log\Target
```

### PR DESCRIPTION
**Pull request by mstegmeyer**
Adding optional parameters to a constructor is not a breaking change, since child classes do not need to match the signature of the parent. Only non-optional parameters (or parameters with default values before the last required parameter) are a breaking change in a constructor, as here the method call would need to be adjusted

### Small example

```php
class A {
    public function __construct(int $one, int $two = 666) {}
}

class B extends A {
    public function __construct(string $whatever) {
        parent::__construct(1);
    }
}

new B('foo');
new A(2);
```

Adding the parameter `$two` in class `A` here does not have an effect on neither constructing `A` nor `B`.

You can try it out here: https://3v4l.org/QYsC8

fixes https://github.com/Roave/BackwardCompatibilityCheck/issues/978

### CODE REVIEW

File: src/DetectChanges/BCBreak/MethodBased/MethodParameterAdded.php [hunk 1]
```diff
@@ -30,6 +30,17 @@ public function __invoke(ReflectionMethod $fromMethod, ReflectionMethod $toMetho
...
+        // new optional parameters of constructors are not BC breaks,
+        // as the method signature of child classes does not need to match the parent
+        if ($fromMethod->isConstructor()) {
+            foreach ($added as $key => $paramName) {
+                $parameter = $toMethod->getParameter($paramName);
+                if ($parameter->isOptional()) {
+                    unset($added[$key]);
+                }
+            }
+        }
```
Comment (Ocramius) [inline src/DetectChanges/BCBreak/MethodBased/MethodParameterAdded.php]: can this be rewritten to be an `array_filter()` on `$toMethod->getParameters()`, please? 

As it is, this is a lot of added AST, and it therefore heavily weights on mutation tests and code complexity

**Review by Ocramius — APPROVED** [review]

File: src/DetectChanges/BCBreak/MethodBased/MethodParameterAdded.php (hunk 1 above)
Comment (mstegmeyer) [reply src/DetectChanges/BCBreak/MethodBased/MethodParameterAdded.php]: Yes, moved the filtering up and refactored it to an `array_filter`.

But: I decided to keep the outer `if` condition, since for most methods, that obviously aren't constructors, that filtering does not need to run and hog resources.

**Review by Ocramius — APPROVED** [review]
Thanks @mstegmeyer!
