### PR TITLE
#85 fail-safe wrapper around BC compliance checks that access risky/throw-happy reflection API

### LINKED ISSUE #85: Add `Throwable`-safe wrappers around all `Roave\BackwardCompatibility\DetectChanges\BCBreak\*` classes that may crash during reflection operations
The idea is that a BC break should be detected (following the mantra "when in doubt: something is wrong"), and the exception message collected and shown in the report, but without crashing further execution.

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #85

### CODE REVIEW

File: src/Change.php [hunk 1]
```diff
@@ -52,6 +54,12 @@ public static function removed(string $description, bool $isBcBreak) : self
         return new self(self::REMOVED, $description, $isBcBreak);
     }
 
+    public static function skippedDueToFailure(Throwable $failure) : self
+    {
+        // @TODO Note: we may consider importing the full exception for better printing later on
```
Comment (Ocramius) [inline src/Change.php]: Moved to https://github.com/Roave/BackwardCompatibilityCheck/issues/93

**Comment by Ocramius** [comment]
Quoting @asgrim:

 > @ocramius I see good shit happening atm on BCC, but I'm behind on like everything atm
 > I'll catch up but if it's urgent please just merge shit
 > eventuall

So lots of shit, which means :ship:, I suppose :+1:
